apiVersion: v1
kind: Service
metadata:
  name: service-web
  labels:
    app: todo-web
spec:
  type: NodePort
  selector:
    app: todo-web
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 31080
